#30 CSS grid now flips
Joe-Bentley/team_totem pull request #40
Opened 2020-12-02 19:05 UTC by katiemhughes

2020-12-02 19:52 UTC, maddyharrop requested changes
Does the env.txt need to be in the git ignore? i dont think it should be public

2020-12-02 22:52 UTC, Joe-Bentley approved these changes, later dismissed
👏 Love the design

2020-12-03 10:15 UTC, Joe-Bentley approved these changes

2020-12-03 10:16 UTC, Joe-Bentley approved these changes

2020-12-03 10:16 UTC, maddyharrop approved these changes

2020-12-03 10:16 UTC, merged